version: "3.9"
services:
  keyring:
    image: golang:1.26@sha256:26326682769ca980f8f1d3b1f52be2dd1c1d25270e3de3fe0c97d6bb65df3556
    volumes:
      - .:/usr/local/src/keyring
    working_dir: /usr/local/src/keyring
