version: "3.9"
services:
  keyring:
    image: golang:1.19@sha256:3025bf670b8363ec9f1b4c4f27348e6d9b7fec607c47e401e40df816853e743a
    volumes:
      - .:/usr/local/src/keyring
    working_dir: /usr/local/src/keyring
